// Code generated by github.com/99designs/gqlgen, DO NOT EDIT.

package model

import (
	"time"
)

type AuthPayload struct {
	Token string `json:"token"`
	User  *User  `json:"user"`
}

type LoginInput struct {
	Email    string `json:"email"`
	Password string `json:"password"`
}

type Mutation struct {
}

type Query struct {
}

type RegisterInput struct {
	Email    string `json:"email"`
	Username string `json:"username"`
	Password string `json:"password"`
}

type Subscription struct {
}

type User struct {
	ID            string    `json:"id"`
	Email         string    `json:"email"`
	Username      string    `json:"username"`
	FirstName     *string   `json:"firstName,omitempty"`
	LastName      *string   `json:"lastName,omitempty"`
	Bio           *string   `json:"bio,omitempty"`
	AvatarURL     *string   `json:"avatarUrl,omitempty"`
	EmailVerified bool      `json:"emailVerified"`
	OauthProvider *string   `json:"oauthProvider,omitempty"`
	CreatedAt     time.Time `json:"createdAt"`
	UpdatedAt     time.Time `json:"updatedAt"`
}
