package graph

// This file will be automatically regenerated based on the schema, any resolver implementations
// will be copied through when generating and any unknown code will be moved to the end.
// Code generated by github.com/99designs/gqlgen version v0.17.86

import (
	"context"
	"encoding/json"
	"fmt"
	"log"

	"github.com/gulmix/Social-Network/internal/graph/model"
	"github.com/gulmix/Social-Network/internal/middleware"
	"github.com/gulmix/Social-Network/internal/models"
	"github.com/gulmix/Social-Network/internal/pubsub"
)

// Register is the resolver for the register field.
func (r *mutationResolver) Register(ctx context.Context, input model.RegisterInput) (*model.AuthPayload, error) {
	user, token, err := r.AuthService.Register(input.Email, input.Username, input.Password)
	if err != nil {
		return nil, fmt.Errorf("registration failed: %w", err)
	}

	return &model.AuthPayload{
		Token: token,
		User:  toGraphQLUser(user),
	}, nil
}

// Login is the resolver for the login field.
func (r *mutationResolver) Login(ctx context.Context, input model.LoginInput) (*model.AuthPayload, error) {
	user, token, err := r.AuthService.Login(input.Email, input.Password)
	if err != nil {
		return nil, fmt.Errorf("login failed: %w", err)
	}

	return &model.AuthPayload{
		Token: token,
		User:  toGraphQLUser(user),
	}, nil
}

// OauthLogin is the resolver for the oauthLogin field.
func (r *mutationResolver) OauthLogin(ctx context.Context, provider string, code string) (*model.AuthPayload, error) {
	user, token, err := r.AuthService.OAuthLogin(ctx, provider, code)
	if err != nil {
		return nil, fmt.Errorf("oauth login failed: %w", err)
	}

	return &model.AuthPayload{
		Token: token,
		User:  toGraphQLUser(user),
	}, nil
}

// CreatePost is the resolver for the createPost field.
func (r *mutationResolver) CreatePost(ctx context.Context, input model.CreatePostInput) (*model.Post, error) {
	userID, exists := middleware.GetUserIDFromContext(ctx)
	if !exists {
		return nil, fmt.Errorf("unauthorized")
	}

	isPublic := true
	if input.IsPublic != nil {
		isPublic = *input.IsPublic
	}

	post, err := r.PostService.CreatePost(userID, input.Content, input.ImageUrls, isPublic)
	if err != nil {
		return nil, fmt.Errorf("failed to create post: %w", err)
	}

	if err := r.PubSub.Publish(ctx, pubsub.ChannelPostCreated, post); err != nil {
		log.Printf("pubsub: failed to publish postCreated: %v", err)
	}

	return toGraphQLPost(post), nil
}

// UpdatePost is the resolver for the updatePost field.
func (r *mutationResolver) UpdatePost(ctx context.Context, id string, input model.UpdatePostInput) (*model.Post, error) {
	userID, exists := middleware.GetUserIDFromContext(ctx)
	if !exists {
		return nil, fmt.Errorf("unauthorized")
	}

	post, err := r.PostService.UpdatePost(id, userID, input.Content, input.ImageUrls, input.IsPublic)
	if err != nil {
		return nil, fmt.Errorf("failed to update post: %w", err)
	}

	return toGraphQLPost(post), nil
}

// DeletePost is the resolver for the deletePost field.
func (r *mutationResolver) DeletePost(ctx context.Context, id string) (bool, error) {
	userID, exists := middleware.GetUserIDFromContext(ctx)
	if !exists {
		return false, fmt.Errorf("unauthorized")
	}

	if err := r.PostService.DeletePost(id, userID); err != nil {
		return false, fmt.Errorf("failed to delete post: %w", err)
	}

	return true, nil
}

// CreateComment is the resolver for the createComment field.
func (r *mutationResolver) CreateComment(ctx context.Context, input model.CreateCommentInput) (*model.Comment, error) {
	userID, exists := middleware.GetUserIDFromContext(ctx)
	if !exists {
		return nil, fmt.Errorf("unauthorized")
	}

	comment, err := r.CommentService.CreateComment(userID, input.PostID, input.Content, input.ParentID)
	if err != nil {
		return nil, fmt.Errorf("failed to create comment: %w", err)
	}

	channel := fmt.Sprintf(pubsub.ChannelCommentCreated, comment.PostID)
	if err := r.PubSub.Publish(ctx, channel, comment); err != nil {
		log.Printf("pubsub: failed to publish commentCreated: %v", err)
	}

	return toGraphQLComment(comment), nil
}

// UpdateComment is the resolver for the updateComment field.
func (r *mutationResolver) UpdateComment(ctx context.Context, id string, input model.UpdateCommentInput) (*model.Comment, error) {
	userID, exists := middleware.GetUserIDFromContext(ctx)
	if !exists {
		return nil, fmt.Errorf("unauthorized")
	}

	comment, err := r.CommentService.UpdateComment(id, userID, input.Content)
	if err != nil {
		return nil, fmt.Errorf("failed to update comment: %w", err)
	}

	return toGraphQLComment(comment), nil
}

// DeleteComment is the resolver for the deleteComment field.
func (r *mutationResolver) DeleteComment(ctx context.Context, id string) (bool, error) {
	userID, exists := middleware.GetUserIDFromContext(ctx)
	if !exists {
		return false, fmt.Errorf("unauthorized")
	}

	if err := r.CommentService.DeleteComment(id, userID); err != nil {
		return false, fmt.Errorf("failed to delete comment: %w", err)
	}

	return true, nil
}

// LikePost is the resolver for the likePost field.
func (r *mutationResolver) LikePost(ctx context.Context, postID string) (*model.Like, error) {
	userID, exists := middleware.GetUserIDFromContext(ctx)
	if !exists {
		return nil, fmt.Errorf("unauthorized")
	}

	like, err := r.LikeService.LikePost(userID, postID)
	if err != nil {
		return nil, fmt.Errorf("failed to like post: %w", err)
	}

	channel := fmt.Sprintf(pubsub.ChannelLikeAdded, postID)
	if err := r.PubSub.Publish(ctx, channel, like); err != nil {
		log.Printf("pubsub: failed to publish likeAdded: %v", err)
	}

	return toGraphQLLike(like), nil
}

// UnlikePost is the resolver for the unlikePost field.
func (r *mutationResolver) UnlikePost(ctx context.Context, postID string) (bool, error) {
	userID, exists := middleware.GetUserIDFromContext(ctx)
	if !exists {
		return false, fmt.Errorf("unauthorized")
	}

	if err := r.LikeService.UnlikePost(userID, postID); err != nil {
		return false, fmt.Errorf("failed to unlike post: %w", err)
	}

	channel := fmt.Sprintf(pubsub.ChannelLikeRemoved, postID)
	if err := r.PubSub.Publish(ctx, channel, userID); err != nil {
		log.Printf("pubsub: failed to publish likeRemoved: %v", err)
	}

	return true, nil
}

// FollowUser is the resolver for the followUser field.
func (r *mutationResolver) FollowUser(ctx context.Context, userID string) (*model.Follow, error) {
	followerID, exists := middleware.GetUserIDFromContext(ctx)
	if !exists {
		return nil, fmt.Errorf("unauthorized")
	}

	follow, err := r.FollowService.FollowUser(followerID, userID)
	if err != nil {
		return nil, fmt.Errorf("failed to follow user: %w", err)
	}

	channel := fmt.Sprintf(pubsub.ChannelUserFollowed, userID)
	if err := r.PubSub.Publish(ctx, channel, follow); err != nil {
		log.Printf("pubsub: failed to publish userFollowed: %v", err)
	}

	return toGraphQLFollow(follow), nil
}

// UnfollowUser is the resolver for the unfollowUser field.
func (r *mutationResolver) UnfollowUser(ctx context.Context, userID string) (bool, error) {
	followerID, exists := middleware.GetUserIDFromContext(ctx)
	if !exists {
		return false, fmt.Errorf("unauthorized")
	}

	if err := r.FollowService.UnfollowUser(followerID, userID); err != nil {
		return false, fmt.Errorf("failed to unfollow user: %w", err)
	}

	channel := fmt.Sprintf(pubsub.ChannelUserUnfollowed, userID)
	if err := r.PubSub.Publish(ctx, channel, followerID); err != nil {
		log.Printf("pubsub: failed to publish userUnfollowed: %v", err)
	}

	return true, nil
}

// Posts is the resolver for the posts field.
func (r *queryResolver) Posts(ctx context.Context, userID *string, limit *int32, offset *int32) ([]*model.Post, error) {
	limitInt := 20
	if limit != nil {
		limitInt = int(*limit)
	}

	offsetInt := 0
	if offset != nil {
		offsetInt = int(*offset)
	}

	var posts []*models.Post
	var err error

	if userID != nil {
		posts, err = r.PostService.GetUserPosts(*userID, limitInt, offsetInt)
	} else {
		posts, err = r.PostService.GetPosts(limitInt, offsetInt)
	}

	if err != nil {
		return nil, fmt.Errorf("failed to get posts: %w", err)
	}

	return toGraphQLPosts(posts), nil
}

// Post is the resolver for the post field.
func (r *queryResolver) Post(ctx context.Context, id string) (*model.Post, error) {
	post, err := r.PostService.GetPostByID(id)
	if err != nil {
		return nil, fmt.Errorf("failed to get post: %w", err)
	}

	return toGraphQLPost(post), nil
}

// UserPosts is the resolver for the userPosts field.
func (r *queryResolver) UserPosts(ctx context.Context, userID string, limit *int32, offset *int32) ([]*model.Post, error) {
	limitInt := 20
	if limit != nil {
		limitInt = int(*limit)
	}

	offsetInt := 0
	if offset != nil {
		offsetInt = int(*offset)
	}

	posts, err := r.PostService.GetUserPosts(userID, limitInt, offsetInt)
	if err != nil {
		return nil, fmt.Errorf("failed to get user posts: %w", err)
	}

	return toGraphQLPosts(posts), nil
}

// Comments is the resolver for the comments field.
func (r *queryResolver) Comments(ctx context.Context, postID string, limit *int32, offset *int32) ([]*model.Comment, error) {
	limitInt := 20
	if limit != nil {
		limitInt = int(*limit)
	}

	offsetInt := 0
	if offset != nil {
		offsetInt = int(*offset)
	}

	comments, err := r.CommentService.GetCommentsByPostID(postID, limitInt, offsetInt)
	if err != nil {
		return nil, fmt.Errorf("failed to get comments: %w", err)
	}

	return toGraphQLComments(comments), nil
}

// Comment is the resolver for the comment field.
func (r *queryResolver) Comment(ctx context.Context, id string) (*model.Comment, error) {
	comment, err := r.CommentService.GetCommentByID(id)
	if err != nil {
		return nil, fmt.Errorf("failed to get comment: %w", err)
	}

	return toGraphQLComment(comment), nil
}

// Feed is the resolver for the feed field.
func (r *queryResolver) Feed(ctx context.Context, limit *int32, offset *int32) ([]*model.Post, error) {
	userID, exists := middleware.GetUserIDFromContext(ctx)
	if !exists {
		return nil, fmt.Errorf("unauthorized")
	}

	limitInt := 20
	if limit != nil {
		limitInt = int(*limit)
	}

	offsetInt := 0
	if offset != nil {
		offsetInt = int(*offset)
	}

	posts, err := r.PostService.GetFeed(userID, limitInt, offsetInt)
	if err != nil {
		return nil, fmt.Errorf("failed to get feed: %w", err)
	}

	return toGraphQLPosts(posts), nil
}

// User is the resolver for the user field.
func (r *queryResolver) User(ctx context.Context, id string) (*model.User, error) {
	user, err := r.UserService.GetUserByID(id)
	if err != nil {
		return nil, fmt.Errorf("failed to get user: %w", err)
	}

	return toGraphQLUser(user), nil
}

// Users is the resolver for the users field.
func (r *queryResolver) Users(ctx context.Context) ([]*model.User, error) {
	users, err := r.UserService.GetAllUsers()
	if err != nil {
		return nil, fmt.Errorf("failed to get users: %w", err)
	}

	return toGraphQLUsers(users), nil
}

// Followers is the resolver for the followers field.
func (r *queryResolver) Followers(ctx context.Context, userID string) ([]*model.User, error) {
	followers, err := r.FollowService.GetFollowers(userID)
	if err != nil {
		return nil, fmt.Errorf("failed to get followers: %w", err)
	}

	return toGraphQLUsers(followers), nil
}

// Following is the resolver for the following field.
func (r *queryResolver) Following(ctx context.Context, userID string) ([]*model.User, error) {
	following, err := r.FollowService.GetFollowing(userID)
	if err != nil {
		return nil, fmt.Errorf("failed to get following: %w", err)
	}

	return toGraphQLUsers(following), nil
}

// IsFollowing is the resolver for the isFollowing field.
func (r *queryResolver) IsFollowing(ctx context.Context, userID string) (bool, error) {
	currentUserID, exists := middleware.GetUserIDFromContext(ctx)
	if !exists {
		return false, fmt.Errorf("unauthorized")
	}

	return r.FollowService.IsFollowing(currentUserID, userID)
}

// IsLiked is the resolver for the isLiked field.
func (r *queryResolver) IsLiked(ctx context.Context, postID string) (bool, error) {
	currentUserID, exists := middleware.GetUserIDFromContext(ctx)
	if !exists {
		return false, fmt.Errorf("unauthorized")
	}

	return r.LikeService.IsLiked(currentUserID, postID)
}

// Likes is the resolver for the likes field.
func (r *queryResolver) Likes(ctx context.Context, postID string) ([]*model.Like, error) {
	likes, err := r.LikeService.GetLikesByPostID(postID)
	if err != nil {
		return nil, fmt.Errorf("failed to get likes: %w", err)
	}

	return toGraphQLLikes(likes), nil
}

// Me is the resolver for the me field.
func (r *queryResolver) Me(ctx context.Context) (*model.User, error) {
	userID, exists := middleware.GetUserIDFromContext(ctx)
	if !exists {
		return nil, fmt.Errorf("unauthorized")
	}

	user, err := r.UserService.GetUserByID(userID)
	if err != nil {
		return nil, fmt.Errorf("failed to get current user: %w", err)
	}

	return toGraphQLUser(user), nil
}

// Mutation returns MutationResolver implementation.
func (r *Resolver) Mutation() MutationResolver { return &mutationResolver{r} }

// Query returns QueryResolver implementation.
func (r *Resolver) Query() QueryResolver { return &queryResolver{r} }

// Subscription returns SubscriptionResolver implementation.
func (r *Resolver) Subscription() SubscriptionResolver { return &subscriptionResolver{r} }

type mutationResolver struct{ *Resolver }
type queryResolver struct{ *Resolver }
type subscriptionResolver struct{ *Resolver }

// UserUpdated notifies when the currently authenticated user's profile changes.
func (r *subscriptionResolver) UserUpdated(ctx context.Context) (<-chan *model.User, error) {
	userID, exists := middleware.GetUserIDFromContext(ctx)
	if !exists {
		return nil, fmt.Errorf("unauthorized")
	}

	ch := make(chan *model.User, 1)
	channel := fmt.Sprintf(pubsub.ChannelUserUpdated, userID)
	msgCh := r.PubSub.Subscribe(ctx, channel)

	go func() {
		defer close(ch)
		for msg := range msgCh {
			var u models.User
			if err := json.Unmarshal([]byte(msg), &u); err != nil {
				log.Printf("pubsub: failed to decode userUpdated: %v", err)
				continue
			}
			select {
			case ch <- toGraphQLUser(&u):
			case <-ctx.Done():
				return
			}
		}
	}()

	return ch, nil
}

// PostCreated notifies when any new post is created.
func (r *subscriptionResolver) PostCreated(ctx context.Context) (<-chan *model.Post, error) {
	ch := make(chan *model.Post, 1)
	msgCh := r.PubSub.Subscribe(ctx, pubsub.ChannelPostCreated)

	go func() {
		defer close(ch)
		for msg := range msgCh {
			var p models.Post
			if err := json.Unmarshal([]byte(msg), &p); err != nil {
				log.Printf("pubsub: failed to decode postCreated: %v", err)
				continue
			}
			select {
			case ch <- toGraphQLPost(&p):
			case <-ctx.Done():
				return
			}
		}
	}()

	return ch, nil
}

// CommentCreated notifies when a new comment is added to the given post.
func (r *subscriptionResolver) CommentCreated(ctx context.Context, postID string) (<-chan *model.Comment, error) {
	ch := make(chan *model.Comment, 1)
	channel := fmt.Sprintf(pubsub.ChannelCommentCreated, postID)
	msgCh := r.PubSub.Subscribe(ctx, channel)

	go func() {
		defer close(ch)
		for msg := range msgCh {
			var c models.Comment
			if err := json.Unmarshal([]byte(msg), &c); err != nil {
				log.Printf("pubsub: failed to decode commentCreated: %v", err)
				continue
			}
			select {
			case ch <- toGraphQLComment(&c):
			case <-ctx.Done():
				return
			}
		}
	}()

	return ch, nil
}

// LikeAdded notifies when a like is added to the given post.
func (r *subscriptionResolver) LikeAdded(ctx context.Context, postID string) (<-chan *model.Like, error) {
	ch := make(chan *model.Like, 1)
	channel := fmt.Sprintf(pubsub.ChannelLikeAdded, postID)
	msgCh := r.PubSub.Subscribe(ctx, channel)

	go func() {
		defer close(ch)
		for msg := range msgCh {
			var l models.Like
			if err := json.Unmarshal([]byte(msg), &l); err != nil {
				log.Printf("pubsub: failed to decode likeAdded: %v", err)
				continue
			}
			select {
			case ch <- toGraphQLLike(&l):
			case <-ctx.Done():
				return
			}
		}
	}()

	return ch, nil
}

// LikeRemoved notifies when a like is removed from the given post.
// Returns the ID of the user who unliked the post.
func (r *subscriptionResolver) LikeRemoved(ctx context.Context, postID string) (<-chan string, error) {
	ch := make(chan string, 1)
	channel := fmt.Sprintf(pubsub.ChannelLikeRemoved, postID)
	msgCh := r.PubSub.Subscribe(ctx, channel)

	go func() {
		defer close(ch)
		for msg := range msgCh {
			var userID string
			if err := json.Unmarshal([]byte(msg), &userID); err != nil {
				log.Printf("pubsub: failed to decode likeRemoved: %v", err)
				continue
			}
			select {
			case ch <- userID:
			case <-ctx.Done():
				return
			}
		}
	}()

	return ch, nil
}

// UserFollowed notifies when someone follows the given user.
func (r *subscriptionResolver) UserFollowed(ctx context.Context, userID string) (<-chan *model.Follow, error) {
	ch := make(chan *model.Follow, 1)
	channel := fmt.Sprintf(pubsub.ChannelUserFollowed, userID)
	msgCh := r.PubSub.Subscribe(ctx, channel)

	go func() {
		defer close(ch)
		for msg := range msgCh {
			var f models.Follow
			if err := json.Unmarshal([]byte(msg), &f); err != nil {
				log.Printf("pubsub: failed to decode userFollowed: %v", err)
				continue
			}
			select {
			case ch <- toGraphQLFollow(&f):
			case <-ctx.Done():
				return
			}
		}
	}()

	return ch, nil
}

// UserUnfollowed notifies when someone unfollows the given user.
// Returns the ID of the user who unfollowed.
func (r *subscriptionResolver) UserUnfollowed(ctx context.Context, userID string) (<-chan string, error) {
	ch := make(chan string, 1)
	channel := fmt.Sprintf(pubsub.ChannelUserUnfollowed, userID)
	msgCh := r.PubSub.Subscribe(ctx, channel)

	go func() {
		defer close(ch)
		for msg := range msgCh {
			var followerID string
			if err := json.Unmarshal([]byte(msg), &followerID); err != nil {
				log.Printf("pubsub: failed to decode userUnfollowed: %v", err)
				continue
			}
			select {
			case ch <- followerID:
			case <-ctx.Done():
				return
			}
		}
	}()

	return ch, nil
}
