package graph

// This file will be automatically regenerated based on the schema, any resolver
// implementations
// will be copied through when generating and any unknown code will be moved to the end.
// Code generated by github.com/99designs/gqlgen version v0.17.86

import (
	"context"
	"encoding/json"
	"fmt"
	"log"

	"github.com/gulmix/Social-Network/internal/graph/model"
	"github.com/gulmix/Social-Network/internal/middleware"
	"github.com/gulmix/Social-Network/internal/models"
	"github.com/gulmix/Social-Network/internal/pubsub"
)

// Register is the resolver for the register field.
func (r *mutationResolver) Register(ctx context.Context, input model.RegisterInput) (*model.AuthPayload, error) {
	user, token, err := r.AuthService.Register(input.Email, input.Username, input.Password)
	if err != nil {
		return nil, fmt.Errorf("registration failed: %w", err)
	}

	return &model.AuthPayload{
		Token: token,
		User:  toGraphQLUser(user),
	}, nil
}

// Login is the resolver for the login field.
func (r *mutationResolver) Login(ctx context.Context, input model.LoginInput) (*model.AuthPayload, error) {
	user, token, err := r.AuthService.Login(input.Email, input.Password)
	if err != nil {
		return nil, fmt.Errorf("login failed: %w", err)
	}

	return &model.AuthPayload{
		Token: token,
		User:  toGraphQLUser(user),
	}, nil
}

// OauthLogin is the resolver for the oauthLogin field.
func (r *mutationResolver) OauthLogin(ctx context.Context, provider string, code string) (*model.AuthPayload, error) {
	user, token, err := r.AuthService.OAuthLogin(ctx, provider, code)
	if err != nil {
		return nil, fmt.Errorf("oauth login failed: %w", err)
	}

	return &model.AuthPayload{
		Token: token,
		User:  toGraphQLUser(user),
	}, nil
}

// CreatePost is the resolver for the createPost field.
func (r *mutationResolver) CreatePost(ctx context.Context, input model.CreatePostInput) (*model.Post, error) {
	userID, exists := middleware.GetUserIDFromContext(ctx)
	if !exists {
		return nil, fmt.Errorf("unauthorized")
	}

	isPublic := true
	if input.IsPublic != nil {
		isPublic = *input.IsPublic
	}

	post, err := r.PostService.CreatePost(userID, input.Content, input.ImageUrls, isPublic)
	if err != nil {
		return nil, fmt.Errorf("failed to create post: %w", err)
	}

	if err := r.PubSub.Publish(ctx, pubsub.ChannelPostCreated, post); err != nil {
		log.Printf("pubsub: failed to publish postCreated: %v", err)
	}

	return toGraphQLPost(post), nil
}

// UpdatePost is the resolver for the updatePost field.
func (r *mutationResolver) UpdatePost(ctx context.Context, id string, input model.UpdatePostInput) (*model.Post, error) {
	userID, exists := middleware.GetUserIDFromContext(ctx)
	if !exists {
		return nil, fmt.Errorf("unauthorized")
	}

	post, err := r.PostService.UpdatePost(id, userID, input.Content, input.ImageUrls, input.IsPublic)
	if err != nil {
		return nil, fmt.Errorf("failed to update post: %w", err)
	}

	return toGraphQLPost(post), nil
}

// DeletePost is the resolver for the deletePost field.
func (r *mutationResolver) DeletePost(ctx context.Context, id string) (bool, error) {
	userID, exists := middleware.GetUserIDFromContext(ctx)
	if !exists {
		return false, fmt.Errorf("unauthorized")
	}

	if err := r.PostService.DeletePost(id, userID); err != nil {
		return false, fmt.Errorf("failed to delete post: %w", err)
	}

	return true, nil
}

// CreateComment is the resolver for the createComment field.
func (r *mutationResolver) CreateComment(ctx context.Context, input model.CreateCommentInput) (*model.Comment, error) {
	userID, exists := middleware.GetUserIDFromContext(ctx)
	if !exists {
		return nil, fmt.Errorf("unauthorized")
	}

	comment, err := r.CommentService.CreateComment(userID, input.PostID, input.Content, input.ParentID)
	if err != nil {
		return nil, fmt.Errorf("failed to create comment: %w", err)
	}

	channel := fmt.Sprintf(pubsub.ChannelCommentCreated, comment.PostID)
	if err := r.PubSub.Publish(ctx, channel, comment); err != nil {
		log.Printf("pubsub: failed to publish commentCreated: %v", err)
	}

	return toGraphQLComment(comment), nil
}

// UpdateComment is the resolver for the updateComment field.
func (r *mutationResolver) UpdateComment(ctx context.Context, id string, input model.UpdateCommentInput) (*model.Comment, error) {
	userID, exists := middleware.GetUserIDFromContext(ctx)
	if !exists {
		return nil, fmt.Errorf("unauthorized")
	}

	comment, err := r.CommentService.UpdateComment(id, userID, input.Content)
	if err != nil {
		return nil, fmt.Errorf("failed to update comment: %w", err)
	}

	return toGraphQLComment(comment), nil
}

// DeleteComment is the resolver for the deleteComment field.
func (r *mutationResolver) DeleteComment(ctx context.Context, id string) (bool, error) {
	userID, exists := middleware.GetUserIDFromContext(ctx)
	if !exists {
		return false, fmt.Errorf("unauthorized")
	}

	if err := r.CommentService.DeleteComment(id, userID); err != nil {
		return false, fmt.Errorf("failed to delete comment: %w", err)
	}

	return true, nil
}

// LikePost is the resolver for the likePost field.
func (r *mutationResolver) LikePost(ctx context.Context, postID string) (*model.Like, error) {
	userID, exists := middleware.GetUserIDFromContext(ctx)
	if !exists {
		return nil, fmt.Errorf("unauthorized")
	}

	like, err := r.LikeService.LikePost(userID, postID)
	if err != nil {
		return nil, fmt.Errorf("failed to like post: %w", err)
	}

	channel := fmt.Sprintf(pubsub.ChannelLikeAdded, postID)
	if err := r.PubSub.Publish(ctx, channel, like); err != nil {
		log.Printf("pubsub: failed to publish likeAdded: %v", err)
	}

	return toGraphQLLike(like), nil
}

// UnlikePost is the resolver for the unlikePost field.
func (r *mutationResolver) UnlikePost(ctx context.Context, postID string) (bool, error) {
	userID, exists := middleware.GetUserIDFromContext(ctx)
	if !exists {
		return false, fmt.Errorf("unauthorized")
	}

	if err := r.LikeService.UnlikePost(userID, postID); err != nil {
		return false, fmt.Errorf("failed to unlike post: %w", err)
	}

	channel := fmt.Sprintf(pubsub.ChannelLikeRemoved, postID)
	if err := r.PubSub.Publish(ctx, channel, userID); err != nil {
		log.Printf("pubsub: failed to publish likeRemoved: %v", err)
	}

	return true, nil
}

// FollowUser is the resolver for the followUser field.
func (r *mutationResolver) FollowUser(ctx context.Context, userID string) (*model.Follow, error) {
	followerID, exists := middleware.GetUserIDFromContext(ctx)
	if !exists {
		return nil, fmt.Errorf("unauthorized")
	}

	follow, err := r.FollowService.FollowUser(followerID, userID)
	if err != nil {
		return nil, fmt.Errorf("failed to follow user: %w", err)
	}

	channel := fmt.Sprintf(pubsub.ChannelUserFollowed, userID)
	if err := r.PubSub.Publish(ctx, channel, follow); err != nil {
		log.Printf("pubsub: failed to publish userFollowed: %v", err)
	}

	return toGraphQLFollow(follow), nil
}

// UnfollowUser is the resolver for the unfollowUser field.
func (r *mutationResolver) UnfollowUser(ctx context.Context, userID string) (bool, error) {
	followerID, exists := middleware.GetUserIDFromContext(ctx)
	if !exists {
		return false, fmt.Errorf("unauthorized")
	}

	if err := r.FollowService.UnfollowUser(followerID, userID); err != nil {
		return false, fmt.Errorf("failed to unfollow user: %w", err)
	}

	channel := fmt.Sprintf(pubsub.ChannelUserUnfollowed, userID)
	if err := r.PubSub.Publish(ctx, channel, followerID); err != nil {
		log.Printf("pubsub: failed to publish userUnfollowed: %v", err)
	}

	return true, nil
}

// CreateDirectConversation is the resolver for the createDirectConversation field.
func (r *mutationResolver) CreateDirectConversation(ctx context.Context, userID string) (*model.Conversation, error) {
	currentUserID, exists := middleware.GetUserIDFromContext(ctx)
	if !exists {
		return nil, fmt.Errorf("unauthorized")
	}

	conv, err := r.ConversationService.CreateDirectConversation(currentUserID, userID)
	if err != nil {
		return nil, fmt.Errorf("failed to create conversation: %w", err)
	}

	return toGraphQLConversation(conv), nil
}

// CreateGroupConversation is the resolver for the createGroupConversation field.
func (r *mutationResolver) CreateGroupConversation(ctx context.Context, name string, participantIds []string) (*model.Conversation, error) {
	currentUserID, exists := middleware.GetUserIDFromContext(ctx)
	if !exists {
		return nil, fmt.Errorf("unauthorized")
	}

	conv, err := r.ConversationService.CreateGroupConversation(currentUserID, name, participantIds)
	if err != nil {
		return nil, fmt.Errorf("failed to create group conversation: %w", err)
	}

	return toGraphQLConversation(conv), nil
}

// SendMessage is the resolver for the sendMessage field.
func (r *mutationResolver) SendMessage(ctx context.Context, input model.SendMessageInput) (*model.Message, error) {
	userID, exists := middleware.GetUserIDFromContext(ctx)
	if !exists {
		return nil, fmt.Errorf("unauthorized")
	}

	msg, err := r.MessageService.SendMessage(userID, input.ConversationID, input.Content, input.MediaURL)
	if err != nil {
		return nil, fmt.Errorf("failed to send message: %w", err)
	}

	channel := fmt.Sprintf(pubsub.ChannelMessageReceived, input.ConversationID)
	if err := r.PubSub.Publish(ctx, channel, msg); err != nil {
		log.Printf("pubsub: failed to publish messageReceived: %v", err)
	}

	return toGraphQLMessage(msg), nil
}

// DeleteMessage is the resolver for the deleteMessage field.
func (r *mutationResolver) DeleteMessage(ctx context.Context, id string) (bool, error) {
	userID, exists := middleware.GetUserIDFromContext(ctx)
	if !exists {
		return false, fmt.Errorf("unauthorized")
	}

	if err := r.MessageService.DeleteMessage(id, userID); err != nil {
		return false, fmt.Errorf("failed to delete message: %w", err)
	}

	return true, nil
}

// MarkConversationAsRead is the resolver for the markConversationAsRead field.
func (r *mutationResolver) MarkConversationAsRead(ctx context.Context, conversationID string) (bool, error) {
	userID, exists := middleware.GetUserIDFromContext(ctx)
	if !exists {
		return false, fmt.Errorf("unauthorized")
	}

	if err := r.MessageService.MarkAsRead(conversationID, userID); err != nil {
		return false, fmt.Errorf("failed to mark as read: %w", err)
	}

	return true, nil
}

// CreateGroup is the resolver for the createGroup field.
func (r *mutationResolver) CreateGroup(ctx context.Context, input model.CreateGroupInput) (*model.Group, error) {
	userID, exists := middleware.GetUserIDFromContext(ctx)
	if !exists {
		return nil, fmt.Errorf("unauthorized")
	}

	isPrivate := false
	if input.IsPrivate != nil {
		isPrivate = *input.IsPrivate
	}

	group, err := r.GroupService.CreateGroup(userID, input.Name, input.Description, isPrivate)
	if err != nil {
		return nil, fmt.Errorf("failed to create group: %w", err)
	}

	return toGraphQLGroup(group), nil
}

// UpdateGroup is the resolver for the updateGroup field.
func (r *mutationResolver) UpdateGroup(ctx context.Context, id string, input model.UpdateGroupInput) (*model.Group, error) {
	userID, exists := middleware.GetUserIDFromContext(ctx)
	if !exists {
		return nil, fmt.Errorf("unauthorized")
	}

	name := ""
	if input.Name != nil {
		name = *input.Name
	}

	group, err := r.GroupService.UpdateGroup(id, userID, name, input.Description, input.IsPrivate)
	if err != nil {
		return nil, fmt.Errorf("failed to update group: %w", err)
	}

	return toGraphQLGroup(group), nil
}

// DeleteGroup is the resolver for the deleteGroup field.
func (r *mutationResolver) DeleteGroup(ctx context.Context, id string) (bool, error) {
	userID, exists := middleware.GetUserIDFromContext(ctx)
	if !exists {
		return false, fmt.Errorf("unauthorized")
	}

	if err := r.GroupService.DeleteGroup(id, userID); err != nil {
		return false, fmt.Errorf("failed to delete group: %w", err)
	}

	return true, nil
}

// JoinGroup is the resolver for the joinGroup field.
func (r *mutationResolver) JoinGroup(ctx context.Context, groupID string) (bool, error) {
	userID, exists := middleware.GetUserIDFromContext(ctx)
	if !exists {
		return false, fmt.Errorf("unauthorized")
	}

	if err := r.GroupService.JoinGroup(groupID, userID); err != nil {
		return false, fmt.Errorf("failed to join group: %w", err)
	}

	return true, nil
}

// LeaveGroup is the resolver for the leaveGroup field.
func (r *mutationResolver) LeaveGroup(ctx context.Context, groupID string) (bool, error) {
	userID, exists := middleware.GetUserIDFromContext(ctx)
	if !exists {
		return false, fmt.Errorf("unauthorized")
	}

	if err := r.GroupService.LeaveGroup(groupID, userID); err != nil {
		return false, fmt.Errorf("failed to leave group: %w", err)
	}

	return true, nil
}

// CreateGroupPost is the resolver for the createGroupPost field.
func (r *mutationResolver) CreateGroupPost(ctx context.Context, input model.CreateGroupPostInput) (*model.GroupPost, error) {
	userID, exists := middleware.GetUserIDFromContext(ctx)
	if !exists {
		return nil, fmt.Errorf("unauthorized")
	}

	post, err := r.GroupService.CreateGroupPost(userID, input.GroupID, input.Content, input.ImageUrls)
	if err != nil {
		return nil, fmt.Errorf("failed to create group post: %w", err)
	}

	return toGraphQLGroupPost(post), nil
}

// DeleteGroupPost is the resolver for the deleteGroupPost field.
func (r *mutationResolver) DeleteGroupPost(ctx context.Context, id string) (bool, error) {
	userID, exists := middleware.GetUserIDFromContext(ctx)
	if !exists {
		return false, fmt.Errorf("unauthorized")
	}

	if err := r.GroupService.DeleteGroupPost(id, userID); err != nil {
		return false, fmt.Errorf("failed to delete group post: %w", err)
	}

	return true, nil
}

// CreateEvent is the resolver for the createEvent field.
func (r *mutationResolver) CreateEvent(ctx context.Context, input model.CreateEventInput) (*model.Event, error) {
	userID, exists := middleware.GetUserIDFromContext(ctx)
	if !exists {
		return nil, fmt.Errorf("unauthorized")
	}

	event, err := r.EventService.CreateEvent(userID, input.Title, input.Description, input.Location, input.GroupID, input.StartTime, input.EndTime)
	if err != nil {
		return nil, fmt.Errorf("failed to create event: %w", err)
	}

	return toGraphQLEvent(event), nil
}

// UpdateEvent is the resolver for the updateEvent field.
func (r *mutationResolver) UpdateEvent(ctx context.Context, id string, input model.UpdateEventInput) (*model.Event, error) {
	userID, exists := middleware.GetUserIDFromContext(ctx)
	if !exists {
		return nil, fmt.Errorf("unauthorized")
	}

	title := ""
	if input.Title != nil {
		title = *input.Title
	}

	event, err := r.EventService.UpdateEvent(id, userID, title, input.Description, input.Location, input.StartTime, input.EndTime)
	if err != nil {
		return nil, fmt.Errorf("failed to update event: %w", err)
	}

	return toGraphQLEvent(event), nil
}

// DeleteEvent is the resolver for the deleteEvent field.
func (r *mutationResolver) DeleteEvent(ctx context.Context, id string) (bool, error) {
	userID, exists := middleware.GetUserIDFromContext(ctx)
	if !exists {
		return false, fmt.Errorf("unauthorized")
	}

	if err := r.EventService.DeleteEvent(id, userID); err != nil {
		return false, fmt.Errorf("failed to delete event: %w", err)
	}

	return true, nil
}

// RespondToEvent is the resolver for the respondToEvent field.
func (r *mutationResolver) RespondToEvent(ctx context.Context, eventID string, status string) (bool, error) {
	userID, exists := middleware.GetUserIDFromContext(ctx)
	if !exists {
		return false, fmt.Errorf("unauthorized")
	}

	if err := r.EventService.RespondToEvent(eventID, userID, status); err != nil {
		return false, fmt.Errorf("failed to respond to event: %w", err)
	}

	return true, nil
}

// CancelEventAttendance is the resolver for the cancelEventAttendance field.
func (r *mutationResolver) CancelEventAttendance(ctx context.Context, eventID string) (bool, error) {
	userID, exists := middleware.GetUserIDFromContext(ctx)
	if !exists {
		return false, fmt.Errorf("unauthorized")
	}

	if err := r.EventService.CancelAttendance(eventID, userID); err != nil {
		return false, fmt.Errorf("failed to cancel attendance: %w", err)
	}

	return true, nil
}

// MarkNotificationAsRead is the resolver for the markNotificationAsRead field.
func (r *mutationResolver) MarkNotificationAsRead(ctx context.Context, id string) (bool, error) {
	userID, exists := middleware.GetUserIDFromContext(ctx)
	if !exists {
		return false, fmt.Errorf("unauthorized")
	}

	if err := r.NotificationService.MarkAsRead(id, userID); err != nil {
		return false, fmt.Errorf("failed to mark notification as read: %w", err)
	}

	return true, nil
}

// MarkAllNotificationsAsRead is the resolver for the markAllNotificationsAsRead field.
func (r *mutationResolver) MarkAllNotificationsAsRead(ctx context.Context) (bool, error) {
	userID, exists := middleware.GetUserIDFromContext(ctx)
	if !exists {
		return false, fmt.Errorf("unauthorized")
	}

	if err := r.NotificationService.MarkAllAsRead(userID); err != nil {
		return false, fmt.Errorf("failed to mark all notifications as read: %w", err)
	}

	return true, nil
}

// CreateStory is the resolver for the createStory field.
func (r *mutationResolver) CreateStory(ctx context.Context, input model.CreateStoryInput) (*model.Story, error) {
	userID, exists := middleware.GetUserIDFromContext(ctx)
	if !exists {
		return nil, fmt.Errorf("unauthorized")
	}

	story, err := r.StoryService.CreateStory(userID, input.MediaURL, input.Content)
	if err != nil {
		return nil, fmt.Errorf("failed to create story: %w", err)
	}

	if err := r.PubSub.Publish(ctx, pubsub.ChannelStoryCreated, story); err != nil {
		log.Printf("pubsub: failed to publish storyCreated: %v", err)
	}

	return toGraphQLStory(story), nil
}

// DeleteStory is the resolver for the deleteStory field.
func (r *mutationResolver) DeleteStory(ctx context.Context, id string) (bool, error) {
	userID, exists := middleware.GetUserIDFromContext(ctx)
	if !exists {
		return false, fmt.Errorf("unauthorized")
	}

	if err := r.StoryService.DeleteStory(id, userID); err != nil {
		return false, fmt.Errorf("failed to delete story: %w", err)
	}

	return true, nil
}

// ViewStory is the resolver for the viewStory field.
func (r *mutationResolver) ViewStory(ctx context.Context, storyID string) (bool, error) {
	userID, exists := middleware.GetUserIDFromContext(ctx)
	if !exists {
		return false, fmt.Errorf("unauthorized")
	}

	if err := r.StoryService.ViewStory(storyID, userID); err != nil {
		return false, fmt.Errorf("failed to view story: %w", err)
	}

	return true, nil
}

// Me is the resolver for the me field.
func (r *queryResolver) Me(ctx context.Context) (*model.User, error) {
	userID, exists := middleware.GetUserIDFromContext(ctx)
	if !exists {
		return nil, fmt.Errorf("unauthorized")
	}

	user, err := r.UserService.GetUserByID(userID)
	if err != nil {
		return nil, fmt.Errorf("failed to get current user: %w", err)
	}

	return toGraphQLUser(user), nil
}

// User is the resolver for the user field.
func (r *queryResolver) User(ctx context.Context, id string) (*model.User, error) {
	user, err := r.UserService.GetUserByID(id)
	if err != nil {
		return nil, fmt.Errorf("failed to get user: %w", err)
	}

	return toGraphQLUser(user), nil
}

// Users is the resolver for the users field.
func (r *queryResolver) Users(ctx context.Context) ([]*model.User, error) {
	users, err := r.UserService.GetAllUsers()
	if err != nil {
		return nil, fmt.Errorf("failed to get users: %w", err)
	}

	return toGraphQLUsers(users), nil
}

// Posts is the resolver for the posts field.
func (r *queryResolver) Posts(ctx context.Context, userID *string, limit *int32, offset *int32) ([]*model.Post, error) {
	limitInt := 20
	if limit != nil {
		limitInt = int(*limit)
	}

	offsetInt := 0
	if offset != nil {
		offsetInt = int(*offset)
	}

	var posts []*models.Post
	var err error

	if userID != nil {
		posts, err = r.PostService.GetUserPosts(*userID, limitInt, offsetInt)
	} else {
		posts, err = r.PostService.GetPosts(limitInt, offsetInt)
	}

	if err != nil {
		return nil, fmt.Errorf("failed to get posts: %w", err)
	}

	return toGraphQLPosts(posts), nil
}

// Post is the resolver for the post field.
func (r *queryResolver) Post(ctx context.Context, id string) (*model.Post, error) {
	post, err := r.PostService.GetPostByID(id)
	if err != nil {
		return nil, fmt.Errorf("failed to get post: %w", err)
	}

	return toGraphQLPost(post), nil
}

// UserPosts is the resolver for the userPosts field.
func (r *queryResolver) UserPosts(ctx context.Context, userID string, limit *int32, offset *int32) ([]*model.Post, error) {
	limitInt := 20
	if limit != nil {
		limitInt = int(*limit)
	}

	offsetInt := 0
	if offset != nil {
		offsetInt = int(*offset)
	}

	posts, err := r.PostService.GetUserPosts(userID, limitInt, offsetInt)
	if err != nil {
		return nil, fmt.Errorf("failed to get user posts: %w", err)
	}

	return toGraphQLPosts(posts), nil
}

// Feed is the resolver for the feed field.
func (r *queryResolver) Feed(ctx context.Context, limit *int32, offset *int32) ([]*model.Post, error) {
	userID, exists := middleware.GetUserIDFromContext(ctx)
	if !exists {
		return nil, fmt.Errorf("unauthorized")
	}

	limitInt := 20
	if limit != nil {
		limitInt = int(*limit)
	}

	offsetInt := 0
	if offset != nil {
		offsetInt = int(*offset)
	}

	posts, err := r.PostService.GetFeed(userID, limitInt, offsetInt)
	if err != nil {
		return nil, fmt.Errorf("failed to get feed: %w", err)
	}

	return toGraphQLPosts(posts), nil
}

// Comments is the resolver for the comments field.
func (r *queryResolver) Comments(ctx context.Context, postID string, limit *int32, offset *int32) ([]*model.Comment, error) {
	limitInt := 20
	if limit != nil {
		limitInt = int(*limit)
	}

	offsetInt := 0
	if offset != nil {
		offsetInt = int(*offset)
	}

	comments, err := r.CommentService.GetCommentsByPostID(postID, limitInt, offsetInt)
	if err != nil {
		return nil, fmt.Errorf("failed to get comments: %w", err)
	}

	return toGraphQLComments(comments), nil
}

// Comment is the resolver for the comment field.
func (r *queryResolver) Comment(ctx context.Context, id string) (*model.Comment, error) {
	comment, err := r.CommentService.GetCommentByID(id)
	if err != nil {
		return nil, fmt.Errorf("failed to get comment: %w", err)
	}

	return toGraphQLComment(comment), nil
}

// Likes is the resolver for the likes field.
func (r *queryResolver) Likes(ctx context.Context, postID string) ([]*model.Like, error) {
	likes, err := r.LikeService.GetLikesByPostID(postID)
	if err != nil {
		return nil, fmt.Errorf("failed to get likes: %w", err)
	}

	return toGraphQLLikes(likes), nil
}

// IsLiked is the resolver for the isLiked field.
func (r *queryResolver) IsLiked(ctx context.Context, postID string) (bool, error) {
	currentUserID, exists := middleware.GetUserIDFromContext(ctx)
	if !exists {
		return false, fmt.Errorf("unauthorized")
	}

	return r.LikeService.IsLiked(currentUserID, postID)
}

// Followers is the resolver for the followers field.
func (r *queryResolver) Followers(ctx context.Context, userID string) ([]*model.User, error) {
	followers, err := r.FollowService.GetFollowers(userID)
	if err != nil {
		return nil, fmt.Errorf("failed to get followers: %w", err)
	}

	return toGraphQLUsers(followers), nil
}

// Following is the resolver for the following field.
func (r *queryResolver) Following(ctx context.Context, userID string) ([]*model.User, error) {
	following, err := r.FollowService.GetFollowing(userID)
	if err != nil {
		return nil, fmt.Errorf("failed to get following: %w", err)
	}

	return toGraphQLUsers(following), nil
}

// IsFollowing is the resolver for the isFollowing field.
func (r *queryResolver) IsFollowing(ctx context.Context, userID string) (bool, error) {
	currentUserID, exists := middleware.GetUserIDFromContext(ctx)
	if !exists {
		return false, fmt.Errorf("unauthorized")
	}

	return r.FollowService.IsFollowing(currentUserID, userID)
}

// Conversations is the resolver for the conversations field.
func (r *queryResolver) Conversations(ctx context.Context, limit *int32, offset *int32) ([]*model.Conversation, error) {
	userID, exists := middleware.GetUserIDFromContext(ctx)
	if !exists {
		return nil, fmt.Errorf("unauthorized")
	}

	limitInt := 20
	if limit != nil {
		limitInt = int(*limit)
	}
	offsetInt := 0
	if offset != nil {
		offsetInt = int(*offset)
	}

	convs, err := r.ConversationService.GetUserConversations(userID, limitInt, offsetInt)
	if err != nil {
		return nil, fmt.Errorf("failed to get conversations: %w", err)
	}

	result := make([]*model.Conversation, len(convs))
	for i, conv := range convs {
		result[i] = toGraphQLConversation(conv)
	}
	return result, nil
}

// Conversation is the resolver for the conversation field.
func (r *queryResolver) Conversation(ctx context.Context, id string) (*model.Conversation, error) {
	userID, exists := middleware.GetUserIDFromContext(ctx)
	if !exists {
		return nil, fmt.Errorf("unauthorized")
	}

	conv, err := r.ConversationService.GetConversation(id, userID)
	if err != nil {
		return nil, fmt.Errorf("failed to get conversation: %w", err)
	}

	return toGraphQLConversation(conv), nil
}

// Messages is the resolver for the messages field.
func (r *queryResolver) Messages(ctx context.Context, conversationID string, limit *int32, offset *int32) ([]*model.Message, error) {
	userID, exists := middleware.GetUserIDFromContext(ctx)
	if !exists {
		return nil, fmt.Errorf("unauthorized")
	}

	limitInt := 50
	if limit != nil {
		limitInt = int(*limit)
	}
	offsetInt := 0
	if offset != nil {
		offsetInt = int(*offset)
	}

	msgs, err := r.MessageService.GetMessages(userID, conversationID, limitInt, offsetInt)
	if err != nil {
		return nil, fmt.Errorf("failed to get messages: %w", err)
	}

	return toGraphQLMessages(msgs), nil
}

// Groups is the resolver for the groups field.
func (r *queryResolver) Groups(ctx context.Context, limit *int32, offset *int32) ([]*model.Group, error) {
	limitInt := 20
	if limit != nil {
		limitInt = int(*limit)
	}
	offsetInt := 0
	if offset != nil {
		offsetInt = int(*offset)
	}

	groups, err := r.GroupService.GetGroups(limitInt, offsetInt)
	if err != nil {
		return nil, fmt.Errorf("failed to get groups: %w", err)
	}

	return toGraphQLGroups(groups), nil
}

// Group is the resolver for the group field.
func (r *queryResolver) Group(ctx context.Context, id string) (*model.Group, error) {
	group, err := r.GroupService.GetGroup(id)
	if err != nil {
		return nil, fmt.Errorf("failed to get group: %w", err)
	}

	return toGraphQLGroup(group), nil
}

// MyGroups is the resolver for the myGroups field.
func (r *queryResolver) MyGroups(ctx context.Context) ([]*model.Group, error) {
	userID, exists := middleware.GetUserIDFromContext(ctx)
	if !exists {
		return nil, fmt.Errorf("unauthorized")
	}

	groups, err := r.GroupService.GetUserGroups(userID)
	if err != nil {
		return nil, fmt.Errorf("failed to get user groups: %w", err)
	}

	return toGraphQLGroups(groups), nil
}

// GroupMembers is the resolver for the groupMembers field.
func (r *queryResolver) GroupMembers(ctx context.Context, groupID string) ([]*model.GroupMember, error) {
	members, err := r.GroupService.GetMembers(groupID)
	if err != nil {
		return nil, fmt.Errorf("failed to get group members: %w", err)
	}

	result := make([]*model.GroupMember, len(members))
	for i, m := range members {
		result[i] = &model.GroupMember{
			ID:       m.ID,
			Role:     m.Role,
			JoinedAt: m.JoinedAt,
		}
	}
	return result, nil
}

// GroupPosts is the resolver for the groupPosts field.
func (r *queryResolver) GroupPosts(ctx context.Context, groupID string, limit *int32, offset *int32) ([]*model.GroupPost, error) {
	limitInt := 20
	if limit != nil {
		limitInt = int(*limit)
	}
	offsetInt := 0
	if offset != nil {
		offsetInt = int(*offset)
	}

	posts, err := r.GroupService.GetGroupPosts(groupID, limitInt, offsetInt)
	if err != nil {
		return nil, fmt.Errorf("failed to get group posts: %w", err)
	}

	return toGraphQLGroupPosts(posts), nil
}

// Events is the resolver for the events field.
func (r *queryResolver) Events(ctx context.Context, limit *int32, offset *int32) ([]*model.Event, error) {
	limitInt := 20
	if limit != nil {
		limitInt = int(*limit)
	}
	offsetInt := 0
	if offset != nil {
		offsetInt = int(*offset)
	}

	events, err := r.EventService.GetUpcomingEvents(limitInt, offsetInt)
	if err != nil {
		return nil, fmt.Errorf("failed to get events: %w", err)
	}

	return toGraphQLEvents(events), nil
}

// Event is the resolver for the event field.
func (r *queryResolver) Event(ctx context.Context, id string) (*model.Event, error) {
	event, err := r.EventService.GetEvent(id)
	if err != nil {
		return nil, fmt.Errorf("failed to get event: %w", err)
	}

	return toGraphQLEvent(event), nil
}

// GroupEvents is the resolver for the groupEvents field.
func (r *queryResolver) GroupEvents(ctx context.Context, groupID string, limit *int32, offset *int32) ([]*model.Event, error) {
	limitInt := 20
	if limit != nil {
		limitInt = int(*limit)
	}
	offsetInt := 0
	if offset != nil {
		offsetInt = int(*offset)
	}

	events, err := r.EventService.GetGroupEvents(groupID, limitInt, offsetInt)
	if err != nil {
		return nil, fmt.Errorf("failed to get group events: %w", err)
	}

	return toGraphQLEvents(events), nil
}

// EventAttendees is the resolver for the eventAttendees field.
func (r *queryResolver) EventAttendees(ctx context.Context, eventID string) ([]*model.EventAttendee, error) {
	attendees, err := r.EventService.GetAttendees(eventID)
	if err != nil {
		return nil, fmt.Errorf("failed to get event attendees: %w", err)
	}

	result := make([]*model.EventAttendee, len(attendees))
	for i, a := range attendees {
		result[i] = &model.EventAttendee{
			ID:        a.ID,
			Status:    a.Status,
			CreatedAt: a.CreatedAt,
		}
	}
	return result, nil
}

// Notifications is the resolver for the notifications field.
func (r *queryResolver) Notifications(ctx context.Context, limit *int32, offset *int32) ([]*model.Notification, error) {
	userID, exists := middleware.GetUserIDFromContext(ctx)
	if !exists {
		return nil, fmt.Errorf("unauthorized")
	}

	limitInt := 20
	if limit != nil {
		limitInt = int(*limit)
	}
	offsetInt := 0
	if offset != nil {
		offsetInt = int(*offset)
	}

	notifs, err := r.NotificationService.GetNotifications(userID, limitInt, offsetInt)
	if err != nil {
		return nil, fmt.Errorf("failed to get notifications: %w", err)
	}

	return toGraphQLNotifications(notifs), nil
}

// UnreadNotificationsCount is the resolver for the unreadNotificationsCount field.
func (r *queryResolver) UnreadNotificationsCount(ctx context.Context) (int32, error) {
	userID, exists := middleware.GetUserIDFromContext(ctx)
	if !exists {
		return 0, fmt.Errorf("unauthorized")
	}

	count, err := r.NotificationService.GetUnreadCount(userID)
	if err != nil {
		return 0, fmt.Errorf("failed to get unread count: %w", err)
	}

	return int32(count), nil
}

// Story is the resolver for the story field.
func (r *queryResolver) Story(ctx context.Context, id string) (*model.Story, error) {
	story, err := r.StoryService.GetStory(id)
	if err != nil {
		return nil, fmt.Errorf("failed to get story: %w", err)
	}

	return toGraphQLStory(story), nil
}

// UserStories is the resolver for the userStories field.
func (r *queryResolver) UserStories(ctx context.Context, userID string) ([]*model.Story, error) {
	stories, err := r.StoryService.GetUserStories(userID)
	if err != nil {
		return nil, fmt.Errorf("failed to get user stories: %w", err)
	}

	return toGraphQLStories(stories), nil
}

// FeedStories is the resolver for the feedStories field.
func (r *queryResolver) FeedStories(ctx context.Context) ([]*model.Story, error) {
	userID, exists := middleware.GetUserIDFromContext(ctx)
	if !exists {
		return nil, fmt.Errorf("unauthorized")
	}

	stories, err := r.StoryService.GetFeedStories(userID)
	if err != nil {
		return nil, fmt.Errorf("failed to get feed stories: %w", err)
	}

	return toGraphQLStories(stories), nil
}

// StoryViews is the resolver for the storyViews field.
func (r *queryResolver) StoryViews(ctx context.Context, storyID string) ([]*model.StoryView, error) {
	userID, exists := middleware.GetUserIDFromContext(ctx)
	if !exists {
		return nil, fmt.Errorf("unauthorized")
	}

	views, err := r.StoryService.GetStoryViews(storyID, userID)
	if err != nil {
		return nil, fmt.Errorf("failed to get story views: %w", err)
	}

	return toGraphQLStoryViews(views), nil
}

// UserUpdated notifies when the currently authenticated user's profile changes.
func (r *subscriptionResolver) UserUpdated(ctx context.Context) (<-chan *model.User, error) {
	userID, exists := middleware.GetUserIDFromContext(ctx)
	if !exists {
		return nil, fmt.Errorf("unauthorized")
	}

	ch := make(chan *model.User, 1)
	channel := fmt.Sprintf(pubsub.ChannelUserUpdated, userID)
	msgCh := r.PubSub.Subscribe(ctx, channel)

	go func() {
		defer close(ch)
		for msg := range msgCh {
			var u models.User
			if err := json.Unmarshal([]byte(msg), &u); err != nil {
				log.Printf("pubsub: failed to decode userUpdated: %v", err)
				continue
			}
			select {
			case ch <- toGraphQLUser(&u):
			case <-ctx.Done():
				return
			}
		}
	}()

	return ch, nil
}

// PostCreated notifies when any new post is created.
func (r *subscriptionResolver) PostCreated(ctx context.Context) (<-chan *model.Post, error) {
	ch := make(chan *model.Post, 1)
	msgCh := r.PubSub.Subscribe(ctx, pubsub.ChannelPostCreated)

	go func() {
		defer close(ch)
		for msg := range msgCh {
			var p models.Post
			if err := json.Unmarshal([]byte(msg), &p); err != nil {
				log.Printf("pubsub: failed to decode postCreated: %v", err)
				continue
			}
			select {
			case ch <- toGraphQLPost(&p):
			case <-ctx.Done():
				return
			}
		}
	}()

	return ch, nil
}

// CommentCreated notifies when a new comment is added to the given post.
func (r *subscriptionResolver) CommentCreated(ctx context.Context, postID string) (<-chan *model.Comment, error) {
	ch := make(chan *model.Comment, 1)
	channel := fmt.Sprintf(pubsub.ChannelCommentCreated, postID)
	msgCh := r.PubSub.Subscribe(ctx, channel)

	go func() {
		defer close(ch)
		for msg := range msgCh {
			var c models.Comment
			if err := json.Unmarshal([]byte(msg), &c); err != nil {
				log.Printf("pubsub: failed to decode commentCreated: %v", err)
				continue
			}
			select {
			case ch <- toGraphQLComment(&c):
			case <-ctx.Done():
				return
			}
		}
	}()

	return ch, nil
}

// LikeAdded notifies when a like is added to the given post.
func (r *subscriptionResolver) LikeAdded(ctx context.Context, postID string) (<-chan *model.Like, error) {
	ch := make(chan *model.Like, 1)
	channel := fmt.Sprintf(pubsub.ChannelLikeAdded, postID)
	msgCh := r.PubSub.Subscribe(ctx, channel)

	go func() {
		defer close(ch)
		for msg := range msgCh {
			var l models.Like
			if err := json.Unmarshal([]byte(msg), &l); err != nil {
				log.Printf("pubsub: failed to decode likeAdded: %v", err)
				continue
			}
			select {
			case ch <- toGraphQLLike(&l):
			case <-ctx.Done():
				return
			}
		}
	}()

	return ch, nil
}

// LikeRemoved notifies when a like is removed from the given post.
func (r *subscriptionResolver) LikeRemoved(ctx context.Context, postID string) (<-chan string, error) {
	ch := make(chan string, 1)
	channel := fmt.Sprintf(pubsub.ChannelLikeRemoved, postID)
	msgCh := r.PubSub.Subscribe(ctx, channel)

	go func() {
		defer close(ch)
		for msg := range msgCh {
			var userID string
			if err := json.Unmarshal([]byte(msg), &userID); err != nil {
				log.Printf("pubsub: failed to decode likeRemoved: %v", err)
				continue
			}
			select {
			case ch <- userID:
			case <-ctx.Done():
				return
			}
		}
	}()

	return ch, nil
}

// UserFollowed notifies when someone follows the given user.
func (r *subscriptionResolver) UserFollowed(ctx context.Context, userID string) (<-chan *model.Follow, error) {
	ch := make(chan *model.Follow, 1)
	channel := fmt.Sprintf(pubsub.ChannelUserFollowed, userID)
	msgCh := r.PubSub.Subscribe(ctx, channel)

	go func() {
		defer close(ch)
		for msg := range msgCh {
			var f models.Follow
			if err := json.Unmarshal([]byte(msg), &f); err != nil {
				log.Printf("pubsub: failed to decode userFollowed: %v", err)
				continue
			}
			select {
			case ch <- toGraphQLFollow(&f):
			case <-ctx.Done():
				return
			}
		}
	}()

	return ch, nil
}

// UserUnfollowed notifies when someone unfollows the given user.
func (r *subscriptionResolver) UserUnfollowed(ctx context.Context, userID string) (<-chan string, error) {
	ch := make(chan string, 1)
	channel := fmt.Sprintf(pubsub.ChannelUserUnfollowed, userID)
	msgCh := r.PubSub.Subscribe(ctx, channel)

	go func() {
		defer close(ch)
		for msg := range msgCh {
			var followerID string
			if err := json.Unmarshal([]byte(msg), &followerID); err != nil {
				log.Printf("pubsub: failed to decode userUnfollowed: %v", err)
				continue
			}
			select {
			case ch <- followerID:
			case <-ctx.Done():
				return
			}
		}
	}()

	return ch, nil
}

// MessageReceived is the resolver for the messageReceived field.
func (r *subscriptionResolver) MessageReceived(ctx context.Context, conversationID string) (<-chan *model.Message, error) {
	userID, exists := middleware.GetUserIDFromContext(ctx)
	if !exists {
		return nil, fmt.Errorf("unauthorized")
	}

	_ = userID

	ch := make(chan *model.Message, 1)
	channel := fmt.Sprintf(pubsub.ChannelMessageReceived, conversationID)
	msgCh := r.PubSub.Subscribe(ctx, channel)

	go func() {
		defer close(ch)
		for msg := range msgCh {
			var m models.Message
			if err := json.Unmarshal([]byte(msg), &m); err != nil {
				log.Printf("pubsub: failed to decode messageReceived: %v", err)
				continue
			}
			select {
			case ch <- toGraphQLMessage(&m):
			case <-ctx.Done():
				return
			}
		}
	}()

	return ch, nil
}

// NotificationReceived is the resolver for the notificationReceived field.
func (r *subscriptionResolver) NotificationReceived(ctx context.Context) (<-chan *model.Notification, error) {
	userID, exists := middleware.GetUserIDFromContext(ctx)
	if !exists {
		return nil, fmt.Errorf("unauthorized")
	}

	ch := make(chan *model.Notification, 1)
	channel := fmt.Sprintf(pubsub.ChannelNotificationReceived, userID)
	msgCh := r.PubSub.Subscribe(ctx, channel)

	go func() {
		defer close(ch)
		for msg := range msgCh {
			var n models.Notification
			if err := json.Unmarshal([]byte(msg), &n); err != nil {
				log.Printf("pubsub: failed to decode notificationReceived: %v", err)
				continue
			}
			select {
			case ch <- toGraphQLNotification(&n):
			case <-ctx.Done():
				return
			}
		}
	}()

	return ch, nil
}

// StoryCreated is the resolver for the storyCreated field.
func (r *subscriptionResolver) StoryCreated(ctx context.Context) (<-chan *model.Story, error) {
	ch := make(chan *model.Story, 1)
	msgCh := r.PubSub.Subscribe(ctx, pubsub.ChannelStoryCreated)

	go func() {
		defer close(ch)
		for msg := range msgCh {
			var s models.Story
			if err := json.Unmarshal([]byte(msg), &s); err != nil {
				log.Printf("pubsub: failed to decode storyCreated: %v", err)
				continue
			}
			select {
			case ch <- toGraphQLStory(&s):
			case <-ctx.Done():
				return
			}
		}
	}()

	return ch, nil
}

// Mutation returns MutationResolver implementation.
func (r *Resolver) Mutation() MutationResolver { return &mutationResolver{r} }

// Query returns QueryResolver implementation.
func (r *Resolver) Query() QueryResolver { return &queryResolver{r} }

// Subscription returns SubscriptionResolver implementation.
func (r *Resolver) Subscription() SubscriptionResolver { return &subscriptionResolver{r} }

type mutationResolver struct{ *Resolver }
type queryResolver struct{ *Resolver }
type subscriptionResolver struct{ *Resolver }
